### ISSUE TITLE
NO PATHOPS FOUND

### ISSUE THREAD

**Issue by freder** [coldtype/st2#20]
- ST2 (v0.12) for Mac (Apple Silicon)
- Blender 4.1

![image](https://github.com/coldtype/st2/assets/724844/d3a5f5a3-faca-4fc3-adfd-dff08ef519fe)

console output:

```
---ST2--- (0, 12)
>>> NO PATHOPS FOUND; please install either skia-pathops or booleanOperations
import:COLDTYPE:fail
```

which is odd because from what I can tell they are bundled with the plugin.

**Comment by gwio** [comment]
Same on win with Blender 4.1 and 4.2 Alpha. St2 v0.12

**Comment by stenson** [comment]
it looks like blender 4.1 has python3.11 embedded (where 4.0 had python3.10), which means the c-built libraries don't work

do these builds work?

- https://coldtype.xyz/st2/releases/ST2-v0-14_mac_silicon.zip
- https://coldtype.xyz/st2/releases/ST2-v0-14_mac_intel.zip
- https://coldtype.xyz/st2/releases/ST2-v0-14_win.zip

**Comment by gwio** [comment]
Thx. This is working again on mac silicon and win on 4.1.

**Comment by freder** [comment]
works on my end as well 👍

**Comment by gwio** [comment]
Can confirm. It worked with 0.14 on win once when I tested it. But I had 0.10 installed with the manual download during the same session. Without restarting, replacing it with 0.14 worked. But no longer after restarting.
But mac version 0.14 still works normal.

**Comment by kurmachu** [comment]
To anyone still waiting for a fix and who hasn't figured this out yet, just installing manually using the [development steps](https://github.com/coldtype/st2?tab=readme-ov-file#development)* works. From what I can tell with my very limited python package experience, it seems the latest zip has compiled libraries for the wrong version of python (they're listed as `cp310` in the zip, which I assume is for python 3.10, and not 3.11. When you pip install manually during the steps, it seems to compile fine, giving a file with `cp311`.). This could be entirely wrong and misguided as I don't really know much about python, so uh use at own discretion but it seems to be working for me.
![image](https://github.com/coldtype/st2/assets/31492625/1d7da781-8d80-4d3d-9447-63e6a9ef5d37)

----------------------------------------------------------
*If you're on windows using powershell make sure you just run `venv/Scripts/Activate.ps1` instead of the source command listed; there's no source for powershell and it gives you a nice prompt label.

**Comment by jayliu50** [comment]
Still not working for me on 4.11.

Went through the new instruction steps in the readme. Even when bundling the add-on myself, it doesn't work on 4.11. The zip file included in this thread also doesn't work, but it does on Blender 4.0.

And having to go through `b3denv` is an absolute nightmare on my computer. It's been extremely difficult to get b3denv to get running on the right version of python (which I assume has to be 3.11+ for Blender 4.1+), and targeting the right version of blender (running on windows where I end up with a bunch of different versions).

Deleting multiple versions of python and blender hasn't helped.

To setting the BLENDER_PATH on b3denv hasn't helped. In fact, b3denv just says 


```
PS Z:\win-code\github\st2> b3denv
 _   ___   _
| |_|_  |_| |___ ___ _ _
| . |_  | . | -_|   | | |
|___|___|___|___|_|_|\_/ v0.0.15
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\b3denv.exe\__main__.py", line 7, in <module>
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\b3denv\__init__.py", line 392, in main
    vars = get_vars(None)
           ^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\b3denv\__init__.py", line 96, in get_vars
    python_folder = os.path.join(parent, version, "python\\bin")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 149, in join
  File "<frozen genericpath>", line 164, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by jayliu50** [comment]
Update: got mine to work after a LOT of troubleshooting.

I think my issue was that I was using a Microsoft Store version of Blender, where the surrounding directories are very much locked down. Not even sure if `b3denv` will work with a MS Store version, but that's another story.

0. Install Blender from the Blender website into its default folder like `C:\Program Files\Blender Foundation\Blender 4.1`
1. Follow the [new steps to install](https://github.com/coldtype/st2?tab=readme-ov-file#development). It's critical that `b3denv` references the Blender in the default folder `C:\Program Files\Blender Foundation\Blender 4.1`. 
2. Add a [custom add-on directory](https://www.youtube.com/watch?v=UlBtcJleTx0&ab_channel=polygoniq) to Blender
3. Copy the resulting `ST2` folder from step 1 over to your custom add-on directory. Note that the custom add-on directory must have a folder called `addons`. The result should be `addons/ST2`. Creating a SymbolicLink on Windows didn't seem to work.

(Why do I keep using the MS Store version? Well, it seems to do auto updates. And also, despite every effort, I can't seem to migrate all my prefs, etc. to the default installation location.)
