### ISSUE TITLE
Can't 'Add new text object' 

### ISSUE THREAD

**Issue by finnbaseball** [coldtype/st2#22]
Hi, really excited to use this. I tried installing but i'm getting an error message after I tried to run my first font. Do i need something else installed? 
Many thanks.

"Python: Traceback (most recent call last):
File "/Users/finn/Library/Application Support/Blender/4.1/scripts/addons/ST2/operations.py", line 238, in execute
to = t.create_live_text(t.two_dimensional())
File "/Users/finn/Library/Application Support/Blender/4.1/scripts/addons/ST2/typesetter.py", line 126, in two_dimensional p.remove_overlap()
File "/Users/finn/Library/Application Support/Blender/4.1/scripts/addons/ST2/inline-packages/coldtype/runon/path.py", line 2136, in removeOverlap return self…_pathop(otherPen=None, operation=BooleanOp.Simplify)
ЛАДАААААААААААААААААААААААААААААААААААААААААААААААААААААА
File "/Users/finn/Library/Application Support/Blender/4.1/scripts/addons/ST2/inline-packages/coldtype/runon/path.py", line 2068, in _pathop
self._val. value = calculate_pathop(self, otherPen, operation)
File "/Users/finn/Library/Application Support/Blender/4.1/scripts/addons/ST2/inline-packages/coldtype/pens/misc.py", line 71, in calculate_pathop
bg = BooleanGlyph)
NameError: name 'BooleanGlyph' is not defined. Did you mean: 'Boolean©p"?

**Comment by stenson** [comment]
Thanks for the report — I can't say I've ever seen something like that before, though it does look like the support libraries are failing to load properly. Are you running Blender on an intel mac?

**Comment by finnbaseball** [comment]
Hey Rob,
Thanks for getting back. It’s an M2 Chip MacBook

**Comment by stenson** [comment]
Could you try installing this updated version? https://coldtype.xyz/st2/releases/ST2-v0-17b.zip — it doesn't include the support libraries (once you install the addon, there’s a button in the addon to install the support libraries), so potentially this would fix the issue on your setup.
